model_name: "bert-small"
version: "1.0.0"
huggingface_repo: "prajjwal1/bert-small"
model_size: "29MB"

model_files:
  - pytorch_model.bin
  - config.json
  - vocab.txt

requirements:
  - transformers==4.30.0
  - torch==2.0.0
  - numpy>=1.24.0
