model_name: "all-MiniLM-L6-v2"
version: "1.0.0"
huggingface_repo: "sentence-transformers/all-MiniLM-L6-v2"
model_size: "90MB"

model_files:
  - pytorch_model.bin
  - config.json
  - vocab.txt

requirements:
  - transformers==4.30.0
  - torch==2.0.0
  - numpy>=1.24.0
