model_name: "whisper-tiny"
version: "1.0.0"
huggingface_repo: "openai"

model_files:
  - pytorch_model.bin
  - config.json
  - vocab.json

requirements:
  - transformers==4.30.0
  - torch==2.0.0
  - numpy>=1.24.0
