model_name: "albert"
version: "1.0.0"
huggingface_repo: "albert-base-v2"
model_size: "90MB"

model_files:
  - pytorch_model.bin
  - config.json
  - vocab.txt

requirements:
  - transformers==4.30.0
  - torch==2.0.0
  - numpy>=1.24.0
